# ===================================================================
# JHipster Custom Spring Cloud Config.
# ===================================================================

# Property used on app startup to check the config server status
configserver:
    name: Cusmtom Registry config server
    status: Connected to the JHipster Registry config server, using https://github.com/kriptonis/jhipster-registry-sample-config !

# Default JWT secret token (to be changed in production!)
jhipster:
    security:
        authentication:
            jwt:
                secret: this-secret-has-been-changed-and-is-top-top-secret
